import { Language } from '../types';

export const SUPPORTED_LANGUAGES: Language[] = [
  "fr", "en", "es", "de", "it", "pt", "ru", "zh", "ja", "ko",
  "ar", "hi", "bn", "pl", "nl", "tr", "sv", "no", "da", "fi",
  "el", "th", "vi", "cs", "hu", "ro", "sk", "he", "uk", "bg",
  "lv", "lt", "sl", "et", "is", "ms", "mt", "tl", "sw", "yi",
  "fa", "km", "my", "am", "ne", "pa", "tk", "uz", "sa"
];

export const LANGUAGE_FLAGS: Record<Language, any> = {
  fr: require('../../assets/langs/fr.png'),
  en: require('../../assets/langs/gb.png'),
  es: require('../../assets/langs/es.png'),
  de: require('../../assets/langs/de.png'),
  it: require('../../assets/langs/it.png'),
  pt: require('../../assets/langs/pt.png'),
  ru: require('../../assets/langs/ru.png'),
  zh: require('../../assets/langs/cn.png'),
  ja: require('../../assets/langs/jp.png'),
  ko: require('../../assets/langs/kr.png'),
  ar: require('../../assets/langs/ae.png'),
  hi: require('../../assets/langs/in.png'),
  bn: require('../../assets/langs/bd.png'),
  pl: require('../../assets/langs/pl.png'),
  nl: require('../../assets/langs/nl.png'),
  tr: require('../../assets/langs/tr.png'),
  sv: require('../../assets/langs/se.png'),
  no: require('../../assets/langs/no.png'),
  da: require('../../assets/langs/dk.png'),
  fi: require('../../assets/langs/fi.png'),
  el: require('../../assets/langs/gr.png'),
  th: require('../../assets/langs/th.png'),
  vi: require('../../assets/langs/vn.png'),
  cs: require('../../assets/langs/cz.png'),
  hu: require('../../assets/langs/hu.png'),
  ro: require('../../assets/langs/ro.png'),
  sk: require('../../assets/langs/sk.png'),
  he: require('../../assets/langs/il.png'),
  uk: require('../../assets/langs/ua.png'),
  bg: require('../../assets/langs/bg.png'),
  lv: require('../../assets/langs/lv.png'),
  lt: require('../../assets/langs/lt.png'),
  sl: require('../../assets/langs/si.png'),
  et: require('../../assets/langs/ee.png'),
  is: require('../../assets/langs/is.png'),
  ms: require('../../assets/langs/my.png'),
  mt: require('../../assets/langs/mt.png'),
  tl: require('../../assets/langs/ph.png'),
  sw: require('../../assets/langs/ke.png'),
  yi: require('../../assets/langs/il.png'),
  fa: require('../../assets/langs/ir.png'),
  km: require('../../assets/langs/kh.png'),
  my: require('../../assets/langs/mm.png'),
  am: require('../../assets/langs/et.png'),
  ne: require('../../assets/langs/np.png'),
  pa: require('../../assets/langs/pk.png'),
  tk: require('../../assets/langs/tm.png'),
  uz: require('../../assets/langs/uz.png'),
  sa: require('../../assets/langs/in.png'),
};

export const TRANSLATIONS: Record<Language, any> = {
  fr: require('../../langs/fr').default,
  en: require('../../langs/en').default,
  es: require('../../langs/es').default,
  de: require('../../langs/de').default,
  it: require('../../langs/it').default,
  pt: require('../../langs/pt').default,
  ru: require('../../langs/ru').default,
  zh: require('../../langs/zh').default,
  ja: require('../../langs/jp').default,
  ko: require('../../langs/ko').default,
  ar: require('../../langs/ar').default,
  hi: require('../../langs/hi').default,
  bn: require('../../langs/bn').default,
  pl: require('../../langs/pl').default,
  nl: require('../../langs/nl').default,
  tr: require('../../langs/tr').default,
  sv: require('../../langs/sv').default,
  no: require('../../langs/no').default,
  da: require('../../langs/da').default,
  fi: require('../../langs/fi').default,
  el: require('../../langs/el').default,
  th: require('../../langs/th').default,
  vi: require('../../langs/vi').default,
  cs: require('../../langs/cs').default,
  hu: require('../../langs/hu').default,
  ro: require('../../langs/ro').default,
  sk: require('../../langs/sk').default,
  he: require('../../langs/he').default,
  uk: require('../../langs/uk').default,
  bg: require('../../langs/bg').default,
  lv: require('../../langs/lv').default,
  lt: require('../../langs/lt').default,
  sl: require('../../langs/sl').default,
  et: require('../../langs/et').default,
  is: require('../../langs/is').default,
  ms: require('../../langs/ms').default,
  mt: require('../../langs/mt').default,
  tl: require('../../langs/tl').default,
  sw: require('../../langs/sw').default,
  yi: require('../../langs/yi').default,
  fa: require('../../langs/fa').default,
  km: require('../../langs/km').default,
  my: require('../../langs/my').default,
  am: require('../../langs/am').default,
  ne: require('../../langs/ne').default,
  pa: require('../../langs/pa').default,
  tk: require('../../langs/tk').default,
  uz: require('../../langs/uz').default,
  sa: require('../../langs/sa').default,
};
